pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  ##Exceptions
  Pack1Version: '1.3.0'
  Pack1PushToNuget: False

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@0
  displayName: Install NuGet Tool

# Restore NuGet packages
- task: NuGetCommand@2
  displayName: Restore NuGet Packages
  inputs:
    restoreSolution: '$(solution)'

# Build solution
- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Prepare publish files
- task: DotNetCoreCLI@2
  displayName: Prepare Publish Files
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/**/Marco.*.Core.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False

# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts

# Publish Marco.Exceptions.Core to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Marco.Exceptions.Core
  condition: eq(variables['Pack1PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Marco.Exceptions.Core.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack2Version
- task: NuGetCommand@2
  displayName: Push Marco.Exceptions.Core to NuGet.org
  condition: eq(variables['Pack1PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Marco.Exceptions.Core.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-marco-exceptions-core'
